### ISSUE TITLE
NGSO

### ISSUE THREAD

**Issue by JuliensLab** [igorauad/link_budget#1]
Hello Igor, great library.
I am interested in using it, but I need to use both GEO and NGSO satellites. Can your library be modified easily to achieve this ?
Do you plan on doing this ? (Otherwise I can fork it and attempt to adapt the code).

Thanks!

**Comment by igorauad** [comment]
Hi @JuliensLab ,

Thanks for your interest in the project. What kind of calculations do you need in NGSO? For example, it would be relatively easy to modify the library to compute the link budget for a specific (static) position of an NGSO satellite. On the other hand, some refactoring would be necessary to return the link budget as a vector result, e.g., the CNR for a range of orbital positions, if that's what you want. 

The current workaround for computing several positions would be to re-run the entire computation for each position. For example, you can use a function like the one below and call it repeatedly with varying parameters.

```python
import linkbudget.cli

def calc_link_budget(params):
    parser = linkbudget.cli.get_parser()
    args = parser.parse_args(params)
    return linkbudget.cli.analyze(args)
```

I have played with NGSO radar targets offline (but haven't pushed the changes to this repo). Also, I've been planning to add support for satellites given by name or TLE data using [Skyfield](https://rhodesmill.org/skyfield/earth-satellites.html) or [Astropy](https://docs.astropy.org/en/stable/coordinates/satellites.html). However, I haven't been able to prioritize these tasks. When I do so, I would add a parameter `--obs-time` to determine the observation time (and hence the satellite position) for the link budget so that you don't have to specify lat/long coordinates.

If you would like to give it a try and submit a pull request, that would be very welcome!

Thanks

**Comment by JuliensLab** [comment]
Hi @igorauad, thanks for your reply.
What I would need is:
Have (lat, lon, alt) as parameters for both the satellite and the ground station. Alt needs to be defined. I assume that it is the distance between the Earth center and the object (but it could be the distance between the WGS84 Earth ellipsoid surface and the object in your implementation). 
We would run the calculation for any location of the satellite and the ground station, as required. We won't use TLEs in this case.

**Comment by igorauad** [comment]
Hi @JuliensLab ,

I finally had a chance to work on this. The current work is on branch `sat_coord`. There are two ways to define the satellite position there:

- By providing the coordinates directly. For that, use the options `--sat-long`, `--sat-lat`, and `--sat-alt`. The altitude is the distance in meters above the reference ellipsoid (WGS84). For backwards compatibility, the latitude and altitude both default to the GEO settings (0 latitude and `35786e3` altitude).
- By prediction through TLE orbital data. To use that, run with option `--sat-tle-name`. That is the name of the satellite on [CelesTrak's TLE database](https://celestrak.org/NORAD/elements/). 

With the TLE approach, the CLI will download the TLE dataset and save it at `~/.link-budget/tle` to speed up future requests. Each request downloads the TLE elements matching the given name, so the downloaded dataset contains matches only. If you are going to be fetching a wide variety of satellites, this will likely create many different datasets on the download directory, each with the set of matches. If that becomes a problem, it is probably better to work with the specific TLE group of interest. For instance, if you run with `--sat-tle-group active`, the search will be restricted to the [dataset of active satellites](https://celestrak.org/NORAD/elements/gp.php?GROUP=active&FORMAT=tle), which is quite comprehensive. In this case, the CLI will download a single dataset file (the active list) and reuse it every time.

I still need to do some extra work before merging this branch. For instance, the calculation of the LNB's polarization skew is still assuming a GEO satellite.

I will post here again once I finally merge it and release a new version.

**Comment by JuliensLab** [comment]
These are great news. Thank you very much. I will look into it asap.

**Comment by igorauad** [comment]
Hi @JuliensLab ,

I decided to merge the abovementioned changes and release a new [minor version on PyPI](https://pypi.org/project/link-budget/#history). The polarity skew calculation for NGSO is still pending, but that is not critical. When I figure that out, I'll release another minor version.

I'll go ahead and close this issue for now. But please don't hesitate to reopen it at any time.

Thanks
